activity/urls.py
from django.urls import path
from . import views

app_name = "activity"

urlpatterns = [
    path('activity/', views.activity, name='activity'),
    path('result/',views.result, name = 'result'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.blog, name='blog'),
    path('id1/',views.article1, name='article1'),
    path('id2/',views.article2, name='article2'),
    path('id3/',views.article3, name='article3'),
    path('response/',views.commentReturn, name="return_comment"),
    
] 

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
    # dilanjutkan ...
]

testimoni/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'testimoni'

urlpatterns = [
    path('', views.index, name='index'),
    #path('add_testi/', views.add_testi, name="add_testi")
    path('testjson_testi/', views.json_testi, name="json_testi")
    # dilanjutkan ...
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include
#from register.forms import RegisterForm
#from register.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('testi/', include('testimoni.urls')),
    path('',include('activity.urls')),
    path('register/',include('register.urls')),
    path('blog/',include('blog.urls')),
    #path('register/formregister', index, {'form_class': RegisterForm}),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Comment(models.Model):
    nama = models.CharField(max_length=100,default="*Tanpa Nama*")
    judul = models.CharField(max_length=100,default="*Tanpa Judul*")
    published_date = models.DateTimeField(default=timezone.now)
    comment = models.CharField(max_length=1000,default="Artikel Bagus")

blog/forms.py
from django import forms
from . import models

class Comment_Form(forms.Form):
    judul = forms.CharField(widget=forms.TextInput(attrs={'required' : 'True', 'class':'form-control',
                                'label' : 'judul comment', 'id':'judul'}))

    comment = forms.CharField(widget=forms.TextInput(attrs={'required' : 'True', 'class':'form-control',
                                'label' : 'comment', 'id':'comment'}))
class Meta:
    model = models.Comment
    fields = ('Comment')  

blog/views.py
import requests
from django.http import JsonResponse
from django.shortcuts import render
from . import models
from . import forms
from django.contrib.auth.models import User

# Create your views here.
def blog(request): 
    return render(request,'blog.html')
def article1(request):
    result = models.Comment.objects.all();
    form=forms.Comment_Form()
    return render(request,'article1.html',{"form":form,"comment":result})
def article2(request):
    result = models.Comment.objects.all();
    form=forms.Comment_Form()
    return render(request,'article2.html',{"form":form,"comment":result})   
def article3(request):
    result = models.Comment.objects.all();
    form=forms.Comment_Form()
    return render(request,'article3.html',{"form":form,"comment":result})

def commentReturn(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = forms.Comment_Form(request.POST)
            if form.is_valid():
                nama = request.user.get_full_name()
                judul = request.POST['judul']
                comment = request.POST['comment']
                result = forms.Comment_Form.objects.create(nama=nama,
                                                             judul= form.data['judul'], 
                                                                comment = form.data['comment'])
                result.save()
                response = JsonResponse({'nama':nama, 'judul':judul,'comment':comment}, safe=False)
                return response
    
    pesan = 'Not Yet Login'
    response = JsonResponse({'status':'false','message':pesan})
    response.status_code = 403
    return response
    # def article1_response(request):
    # return render(request,'')

blog/templates/article1.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
	<div> 
		<div>
			<h1>Tak Perlu Dikupas, Ini 5 Manfaat Konsumsi Kentang Bersama Kulitnya</h1>
			<br/>
			<img style="width:250px; height:200px;" src="{% static 'images\kentang.jpg' %}" class="rounded mx-auto d-block" alt="Kentang">
			<br/>
			<article > 
				Kentang kerap dimasukkan dalam menu makanan sehat. Sayuran akar ini begitu populer dan menjadi salah satu pilihan pengganti nasi. 
				Kentang dapat diolah dengan berbagai cara. Anda dapat menikmati kentang rebus, goreng, kukus, atau dicampur dalam olahan masakan lain. 
				Orang kerap kali mengupas kulit kentang saat hendak mengonsumsinya. Tetapi tahukah Anda bahwa memakan kulit kentang akan menghasilkan lebih banyak 
				serat, vitamin, dan mineral? Kulit kentang tidak mengandung kolesterol atau sejumlah besar lemak.
				Selama Anda mengonsumsinya tanpa bahan tambahan, kulit kentang rendah kalori dan memberikan manfaat kesehatan yang mencakup
				membantu pencernaan, mengelola tekanan darah, menjaga tulang kuat dan menangkal penyakit.
				Nah apa saja yang didapat dari mengonsumsi kentang bersama kulitnya? Berikut manfaat kulit kentang yang berhasil Liputan6.com rangkum dari Live Strong, Jumat(9/8/2019).
			</article></br>
			<h2> Lancarkan pencernaan </h2></br>
			<article>
				Serat dalam kulit kentang dapat membantu pencernaan tetap teratur. Serat adalah bagian selulosa dari makanan yang tidak bisa dicerna oleh tubuh. 
				Ini menambahkan curah dan menyerap air untuk melunakkan tinja sehingga dapat melewati sistem pencernaan dengan lancar dan membantu mencegah sembelit.
				Menurut The American Journal of Clinical Nutrition, yang diterbitkan pada Oktober 2015, serat juga dapat membantu meringankan divertikulitis, 
				sindrom iritasi usus, wasir dan kondisi usus lainnya. Serat makanan juga ditemukan memiliki potensi untuk mengurangi risiko kanker usus besar.
			</article></br>
			<h2> Baik untuk Tulang </h2></br>
			<article>
				Manfaat kesehatan kulit kentang lainnya berasal dari kandungan mineral yang penting untuk pemeliharaan struktur dan kekuatan tulang. 
				Nutrisi ini termasuk magnesium, kalium, fosfor, kalsium, tembaga, besi dan seng. Sekitar 50 hingga 60 persen magnesium di tubuh berada di tulang. 
				Menurut para ahli di National Institutes of Health (NIH), Mengonsumsi kulit kentang dapat membantu menjaga kepadatan tulang dan dapat membantu mengurangi 
				risiko osteoporosis pada wanita setelah menopause. Kalium pada kulit kentang juga memiliki efek menguntungkan pada sistem kerangka dengan mengurangi 
				kehilangan kalsium dari tulang, yang mengarah pada peningkatan kepadatan mineral tulang. Dalam sebuah penelitian yang diterbitkan di Nutrition Journal 
				pada Maret 2015, konsumsi fosfor dapat mendukung peningkatan kandungan mineral tulang dan kepadatan tulang. Kalsium dari kulit kentang diperlukan untuk 
				mendukung struktur dan kekerasan gigi dan tulang. Tembaga, besi, dan seng dalam kulit kentang membantu tubuh mensintesis kolagen, yang diperlukan untuk menyatukan tulang.
			</article></br>
			<h2> Atur Tekanan Darah </h2></br>
			<article>
				Manfaat kesehatan kulit kentang juga termasuk membantu menjaga jantung berfungsi dengan baik. Mengonsumsi kulit kentang dapat membantu 
				mengelola tekanan darah secara alami melalui mineral: kalium, magnesium, dan kalsium. Kalium membantu fungsi otot yang diperlukan untuk melemaskan 
				dinding pembuluh darah. Ini membantu menurunkan tekanan darah. Kalium juga digunakan untuk melakukan sinyal listrik di jantung untuk mengontrol 
				detak jantung yang tidak teratur. Magnesium membantu pembuluh darah rileks dan berperan dalam pengangkutan ion kalsium dan kalium melintasi membran sel. 
				Proses ini penting dalam menjaga ritme jantung normal dan mengatur tekanan darah. Dampak kalsium ditunjukkan dalam ulasan yang menganalisis
				3.048 peserta dari 16 percobaan dan menemukan bahwa peningkatan asupan kalsium menurunkan tekanan darah, bahkan pada orang dengan tingkat tekanan darah normal.
				Bukti ini diterbitkan oleh Grup Hipertensi pada Juni 2015.
			</article></br>
		</div>
		</br>
		<div>
			<form action="{% url 'blog:return_comment' %}" method="POST" id="form-comment">
				{% csrf_token %}
				{{form.as_p}}
				<input class="btn btn-primary" type="submit" style="margin-left: 55px;">
			</form>
		</div>
		<br/>
		<div class="container">
			<div class="row" id="hasil-komentar">	
			</div>
		</div>	
	</div>
	<script>
			$(document).ready(
				$('#form-comment').submit(function (event) {
					event.preventDefault();
					const judul = $('#judul').val();
					const comment = $('#comment').val();
					$.ajax({
                    	method: 'GET',
						data:{
							'judul' : judul,
							'comment' : comment
						},
						url:"/blog/response/",
						success: function (result) {
							let barisKomentar = $('#hasil-komentar');
							barisKomentar.append(
								"<div class='col-6 col-sm-3'><p><b>"+ result.judul + "</b><p></div>" +
								"<div class='col-6 col-sm-3'><p>"+ result.comment + "<p></div>"+
								"<div class='w-100'></div>"+
								"<div class='col-6 col-sm-3'><p>"+ result.nama + "<p></div>"+
								"<div class='col-6 col-sm-3'><p>"+ result.published_date + "<p></div>"
							);
							$("#judul").val("");
							$("#comment").val("");
						},
						statusCode:{
            				403: function(){
            					alert('Please login first!');
            				}
            			}
					});
				})
			);
	</script> 
{% endblock %}

blog/templates/article2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div class="background">
		<h1>Jangan Dibuang, Ini 4 Manfaat Biji Srikaya yang Jarang Diketahui</h1>
		<br/>
		<img style="width:250px; height:200px;" src="{% static 'images\srikaya.jpg' %}" class="rounded mx-auto d-block" alt="Buah Srikaya">
		<br/> 
		<article>
			Srikaya dikenal dari daging buahnya yang berwarna putih yang lembut dan kenyal dengan bagian luarnya yang keras. 
			Buah ini tumbuh di kawasan tropis seperti Asia Tenggara. Buah srikaya memiliki kandungan nutrisi sehat seperti antioksidan hingga vitamin A. 
			Rupanya selain daging buah yang lezat, biji srikaya juga bermanfaat bagi kehidupan sehari-hari. Sebagian besar orang mungkin berpikir 
			biji srikaya tidak berguna, tetapi ternyata biji ini juga memiliki banyak kegunaan yang luar biasa.
			Biji hitam mengkilap dari srikaya memang tak dapat dikonsumsi karena sedikit beracun. Namun, biji ini dapat dimanfaatkan untuk 
			kebutuhan lain seperti membasmi serangga dan hama.
			Berikut manfaat biji srikaya yang belum banyak diketahui, dilansir Liputan6.com dari Stylecraze, Selasa (6/8/2019).
		</article></br>
		<h2>Membasmi Kutu Rambut</h2></br>
		<article>
			Kutu rambut menjadi gangguan tersendiri pada kepala. Kutu ini bisa memengaruhi kulit kepala dan menciptakan sensasi gatal tak tertahankan. 
			Kutu rambut bisa dibasmi dengan shampo atau obat khusus. Namun, ada cara yang lebih alami yaitu menggunakan biji srikaya.
			Caranya: Giling biji srikaya menjadi bentuk bubuk dan campur dengan sedikit air hingga membentuk pasta. Oleskan di kepala dan biarkan 
			selama 10 menit. Cuci bersih dengan air dingin biasa. Proses ini, jika diulang dua kali seminggu selama sebulan akan memberikan 
			hasil yang luar biasa dan membuat kepala Anda benar-benar bebas kutu.
		</article></br>
		<h2> Pengusir serangga </h2></br>
		<article>
			Apakah Anda muak dengan serangan serangga, nyamuk dan semut di rumah? Biji srikaya dapat membantu Anda mengatasi gangguan ini. 
			Campurkan beberapa biji srikaya yang telah dihaluskan menjadi bubuk dalam air dan biarkan selama beberapa hari. Pengusir serangga buatan alami ini 
			sudah siap digunakan. Taburkan campuran di sekitar rumah, terutama di daerah yang sering terdapat serangga. Hasilnya akan instan dan luar biasa 
			mengusir gangguan serangga. Insektisida yang dibuat dari biji srikaya ini harus dijauhkan dari mata karena memiliki potensi untuk membutakan 
			seseorang untuk sementara waktu.
		</article></br>
		<h2> Produksi Bio-Gas </h2></br>
		<article>
			Negara-negara seperti Jerman dan beberapa negara Eropa lainnya menggunakan keajaiban kecil ini untuk tujuan komersial produksi bio gas. 
			Biji buah ini mengandung asam lemak terperangkap yang kaya akan metil-ester yang memicu produksi gas. Biji srikaya memang cukup beracun dan konsumsi 
			yang tidak disengaja dapat menyebabkan sakit perut parah. Jadi saat Anda menikmati srikaya sebagai camilan malam, pertama-tama pastikan untuk membuang 
			semua bijinya dengan hati-hati.
		</article></br>
		<h2>Manfaat buah srikaya</h2></br>
		<article>
			<b>Tinggi antioksidan</b> <br/> Srikaya sarat dengan antioksidan, yang memerangi radikal bebas di tubuh. Tingkat radikal bebas yang tinggi dapat 
			menyebabkan stres oksidatif, yang berhubungan dengan penyakit kronis, termasuk kanker dan penyakit jantung. Senyawa tertentu dalam cherimoya - 
			termasuk asam kaurenoic, flavonoid, karotenoid, dan vitamin C - memiliki efek antioksidan yang kuat.<br/><br/>
			<b>Menambah berat badan sehat</b> <br/> Srikaya baik untuk mereka yang ingin menambah berat badan. Campuran madu dan srikaya ketika dikonsumsi 
			secara teratur akan membantu menambah berat yang dibutuhkan dan kalori yang sangat dibutuhkan.<br/> <br/>
			<b>Mencegah Asma</b> <br/> Srikaya kaya akan vitamin B6, yang membantu mengurangi peradangan bronkial dan membantu mencegah serangan asma.<br/><br/>
			<b>Mencegah Serangan Jantung</b><br/> kandungan magnesium dalam srikaya membantu mempertahankan jantung dari serangan jantung dan dapat membantu 
			mengendurkan otot. Selain itu, vitamin B6 dalam srikaya membantu mencegah pengumpulan homocystein yang juga meminimalkan risiko penyakit jantung.<br/><br/>
			<b>Lancarkan pencernaan</b><br/> Srikaya kaya akan tembaga dan serat makanan, yang membantu pencernaan, membantu meringankan buang air besar dan 
			mengatasi sembelit.<br/><br/>
			<b>Sangat baik untuk penderita diabetes</b><br/> Kelimpahan serat makanan dalam srikaya membantu memperlambat penyerapan gula dan mengurangi risiko
			diabetes tipe-2.<br/><br/>
			<b>Kontrol Tekanan Darah</b> <br/>Srikaya adalah sumber kalium dan magnesium yang baik yang membantu menjaga tingkat tekanan darah tetap terkendali. 
			Bagi mereka dengan tingkat tekanan darah yang berfluktuasi, srikaya akan sangat membantu.<br/><br/>
			<b>Mengurangi Kolesterol</b><br/> Srikaya mengandung niasin dan serat makanan dalam kadar tinggi, yang membantu menurunkan kadar kolesterol 
			secara efektif.<br/><br/>
			<b>Mengobati Anemia</b><br/>Srikaya berfungsi sebagai stimulan, pendingin, ekspektoran, dan hematematik. Selain itu, sumber zat besi yang kaya 
			juga berguna dalam mengobati anemia.
		</article></br>
	</div>
	</br>
	<div>
			<form action="{% url 'blog:return_comment' %}" method="POST" id="form-comment">
				{% csrf_token %}
				{{form.as_p}}
				<input class="btn btn-primary" type="submit">
			</form>
		</div>
		<br/>
		<div class="container">
			<div class="row" id="hasil-komentar">	
				<div class="col-6 col-sm-3">Judul</div>
				<div class="col-6 col-sm-3">.col-6 .col-sm-3</div>
			
				<!-- Force next columns to break to new line -->
				<div class="w-100"></div>
			
				<div class="col-6 col-sm-3">.col-6 .col-sm-3</div>
				<div class="col-6 col-sm-3">.col-6 .col-sm-3</div>
			</div>
		</div>	
	</div>
	<script>
			$(document).ready(
				$('#form-comment').submit(function (event) {
					event.preventDefault();
					const judul = $('#judul').val();
					const comment = $('#comment').val();
					$.ajax({
                    	method: 'GET',
						data:{
							'judul' : judul,
							'comment' : comment
						},
						url:"/blog/response/",
						success: function (result) {
							let barisKomentar = $('#hasil-komentar');
							barisKomentar.append(
								"<div class='col-6 col-sm-3'><p><b>"+ result.judul + "</b><p></div>" +
								"<div class='col-6 col-sm-3'><p>"+ result.comment + "<p></div>"+
								"<div class='w-100'></div>"+
								"<div class='col-6 col-sm-3'><p>"+ result.nama + "<p></div>"+
								"<div class='col-6 col-sm-3'><p>"+ result.published_date + "<p></div>"
							);
							$("#judul").val("");
							$("#comment").val("");
						},
						statusCode:{
            				403: function(){
            					alert('Please login first!');
            				}
            			}
					});
				})
			);
	</script> 
{% endblock %}

blog/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5"> 
    <title>Start Your Healthy Life Here!</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static '\blog\static\css\style.css' %}">
    <link href="{% static 'bootstrap\css\bootstrap.css.min' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
  </head>
  <body>
    <div class = "container">
      <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e3f2fd">
        <a class="navbar-brand" href="{% url 'home:index' %}"><strong>Your </br> Nourishment</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'activity:activity' %}"">Actiytfjbuvity</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'testimoni:index' %}">Testimoni</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Contact Us
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="https://www.instagram.com/hnsmchl/">Instagram</a>
                  <a class="dropdown-item" href="#">Whatsapp</a>
                  <a class="dropdown-item" href="#">Email</a>
                </div>
              </li>
              <li class="nav-item btn btn-primary navlogin">
                <a class="nav-link" href="{% url 'register:login' %}" style="color: white"><b>Login</b></a>
              </li>
            </ul>
          </div>
      </nav>
    </div>
  {% block content %}
  {% endblock %}
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity=" sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>


</html>

blog/templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div class="background">
		<div class ="container">
			<br/>
			<div class="row">
				<div class= "col">
					<img style="width:250px; height:200px;" src="{% static 'images\kentang.jpg' %}" class="rounded mx-auto d-block" alt="Kentang" id="kentang">
				</div>
				<div class= "col">
					<a href= "id1"><h2 id="id1">Tak Perlu Dikupas, Ini 5 Manfaat Konsumsi Kentang Bersama Kulitnya</h2></a>
					<p>On 09 Agustus 2019</p>
					<br />
					<p>By Anugerah Ayu Sendari</p>
				</div>
			</div> 
			<br/>
			<hr/>
			<div class="row">
				<div class= "col">
					<img style="width:250px; height:200px;" src="{% static 'images\srikaya.jpg' %}" class="rounded mx-auto d-block" alt="Buah Srikaya" id ="srikaya">
				</div>
				<div class= "col">
					<a href= "id2"><h2 id="id2">Jangan Dibuang, Ini 4 Manfaat Biji Srikaya yang Jarang Diketahui</h2></a>
					<p>On 06 Agustus 2019</p>
					<br />
					<p>By Anugerah Ayu Sendari</p>
				</div>
			</div>
			<br/>
			<hr/>
			<div class="row">
				<div class= "col">
					<img style="width:250px; height:200px;" src="{% static 'images\buah_naga.jpg' %}" class="rounded mx-auto d-block" alt="Buah Naga" id="buah-naga">
				</div>
				<div class= "col">
					<a href= "id3"><h2 id="id3">Simak, 6 Manfaat Buah Naga yang Penting Bagi Tubuh</h2></a>
					<p>On 06 Juli 2019</p>
					<br />
					<p>By Putu Elmira</p>
				</div>
			</div>
			<br/>
		</div>
	</div>
	<script>
		$("#kentang").hover(function() {
			$( this ).css("width", "80%");
			$( this ).css("height", "100%");
		});
		$("#kentang").mouseout(function() {
			$( this ).css("width", "250px");
			$( this ).css("height", "200px");
		});
		$("#srikaya").hover(function() {
			$( this ).css("width", "50%");
			$( this ).css("height", "120%");
		});
		$("#srikaya").mouseout(function() {
			$( this ).css("width", "250px");
			$( this ).css("height", "200px");
		});
		$("#buah-naga").hover(function() {
			$( this ).css("width", "270px");
			$( this ).css("height", "220px");
		});
		$("#buah-naga").mouseout(function() {
			$( this ).css("width", "250px");
			$( this ).css("height", "200px");
		});
		$("p").click(function(){
			$( this ).css("color","blue");
		});
	</script>
{% endblock %}