home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
    # dilanjutkan ...
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [

    path('', views.index, name='index'),
    path('signin/', views.signin_page, name='signin_page'),
    path('login_func/', views.login_func, name='login_func'),
    path('login_success/', views.login_success, name='login_success'),
    path('logout_success/', views.logout_success, name='logout_success'),
    # dilanjutkan ...
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include
#from register.forms import RegisterForm
#from register.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('testi/', include('testimoni.urls')),
    path('',include('activity.urls')),
    path('register/',include('register.urls')),
    path('blog/',include('blog.urls')),
    #path('register/formregister', index, {'form_class': RegisterForm}),
]

register/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Register(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

register/forms.py
from django import forms
from register.models import Register
from django.contrib.auth.models import User

class RegisterForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','type':'text'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','type':'text'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control login-input'}), max_length=75, required=True)
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control login-input'}), min_length=5, max_length=30, required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control login-input'}), required=True)
    password_check = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control login-input'}), required=True)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password', 'password_check')

    # def clean(self):
    #     cleaned_data = super(RegisterForm, self).clean()
    #     first_name = cleaned_data.get('first_name')
    #     last_name = cleaned_data.get('last_name')
    #     email = cleaned_data.get('email')
    #     username = cleaned_data.get('username')
    #     password = cleaned_data.get('password')
    #     password_check = cleaned_data.get('confirmation_password')

    #     # Username
    #     if User.objects.filter(username=username).exists():
    #         msg = "Sorry, your username is exists"
    #         self.add_error('username', msg)

    #     # Password
    #     if password_check != password:
    #         msg = "Please make sure your password is the same"
    #         self.add_error('confirmation_password', msg)

    #     return cleaned_data

class UserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

register/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse
from register.forms import RegisterForm, UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from register.models import Register
from django.template.defaultfilters import slugify
from django.http import HttpResponseRedirect, HttpResponse
import datetime

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            slug = slugify(username)

            user = User.objects.create_user(username, email, password, first_name = first_name, last_name = last_name)
            user.save()
            form_validated = True
            return redirect('register:login_success')
    else:
        form = RegisterForm()

    return render(request, 'register.html', locals())

def signin_page(request):
    return render(request,'login1.html')

def login_func(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            request.session['my_session'] = username
            return HttpResponseRedirect(reverse('register:login_success'))
        else:
            gagal = "Please check again your username or password"
            return render(request,'login1.html', {'gagal':gagal})
    else:
        form = UserForm()

def login_success(request):
    if request.session.get('my_session') is not None:
        value = request.session['my_session']
    return render(request, 'homepage.html')

def logout_success(request):
    logout(request)
    return redirect('register:signin_page')

register/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Start Your Healthy Life Here!</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity=" sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
    	<a class="navbar-brand" href="{% url 'home:homepage' %}"><strong>Your </br> Nourishment</strong></a>
    	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        	<span class="navbar-toggler-icon"></span>
    	</button>
    	<div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="../activity">Activity</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../blog">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../testi">Testimoni</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Contact Us
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Instagram</a>
                <a class="dropdown-item" href="#">Whatsapp</a>
                <a class="dropdown-item" href="#">Email</a>
              </div>
            </li>
            <li class="nav-item btn btn-primary navlogin">
              <a class="nav-link" href="#" style="color: white"><b>Login</b></a>
            </li>
          </ul>
        </div>
      </nav>
  {% block content %}
  {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity=" sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>


</html>

register/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1> BASE </h1>
{% endblock %}

register/templates/index.html
<!DOCTYPE html>
<html>

<head>
	<title>Nicos</title>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="style.css">

</head>
<body>
	<div class="container">
	    <div class="row">
	      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
	        <div class="card card-signin my-5">
	          <div class="card-body">
	            <h5 class="card-title text-center">Sign In</h5>
	            <form class="form-signin">
	              <div class="form-label-group">
	                <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
	                <label for="inputEmail">Email address</label>
	              </div>

	              <div class="form-label-group">
	                <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
	                <label for="inputPassword">Password</label>
	              </div>

	              <div class="custom-control custom-checkbox mb-3">
	                <small class="register" >Don't have an account? <a href=""> Sign Up </a></small>
	              </div>
	              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>
	              <hr class="my-4">

	            </form>
	          </div>
	        </div>
	      </div>
	    </div>
	</div>
</body>
</html>

register/templates/login1.html
{% extends "base.html" %}
{% load static %}
{% block content %}

	<div class = "container" style = "margin-top:100px">
	<div class="row">
		
		<h3 style = "font-style:justify;">Please Login Here</h3>
		<br/>
		<br/>
		<br/>
			<form action = "{% url 'register:login_func' %}" method = "POST">
				{% csrf_token %}	
	    		<h2> {{gagal}} </h2>
				<div class = 'imgcontainer'>
				<img src = '{% static "image/avatar.png" %}' alt = "avatar" class = "avatar-img">
				</div>
				<div class = "container">
				<input type = "text" placeholder = "Enter Username" aria-label = "Username" name = "username" id = "uname_login" style = "font-family:Roboto;" required>
				<input type = "password" placeholder = "Enter Password" aria-label = "Password" name = "password" id = "pass_login" style = "font-family:Roboto;" required>
				<a href="{% url 'home:index' %}"><button id = "submit-login" type = "submit">Login</button></a>
				<label><input type = "checkbox" checked = "checked">Remember me</label>
				<p class="register" >Don't have an account? <a href="{% url 'register:index' %}"> Sign Up </a></p>
				</div>
				<div class = "container" style = "background-color: #f1f1f1">
				<a href="{% url 'home:index' %}"><button type = "button" class = "cancelbtn">Cancel</button>
				</div>
			</form>
		
	</div>
	</div>
	


	<script type = "text/javascript" src = "{% static 'js/myjs.js' %}"></script>
{% endblock %}

register/templates/process.html
$db = mysqli_connect('localhost', 'root', '', 'taken');
if (isset($_POST['username_check'])) {
    $username = $_POST['username'];
    $sql = "SELECT * FROM users WHERE username ='$username'";
    $results = mysqli_query($db, $sql);
    if (mysqli_num_rows($results) > 0) {
        echo "taken";	
  	}else{
        echo "not_taken";
    }
    exit();
    }
if (isset($_POST['save'])) {
    $username = $_POST['username'];
    $password = $_POST['password'];
    $sql = "SELECT * FROM users WHERE username ='$username'";
    $results = mysqli_query($db, $sql);
    if (mysqli_num_rows($results) > 0) {
        echo "exists";	
        exit();
    }else{
        $query = "INSERT INTO users (username, email, password) 
  	    VALUES ('$username', '$email', '".md5($password)."')";
        $results = mysqli_query($db, $query);
        echo 'Saved!';
        exit();
    }
}

register/templates/register.html
{% extends "base.html" %}
{% load static %}
{% block content %}

	<?php include 'process.php';?>
	<h1 style = "margin-left: 120px; margin-top: 30px; font-family: Roboto; color: black;">Please sign up here</h1>
	<div class = "container" style = "margin-top:120px">
	<div class="row">
    <div class="col-sm-6">
		<form action="{% url 'register:index' %}" method="POST" id = "register_form">
			<div id = "error_msg"></div>
			{% csrf_token %}
			<label for = "first_name">First Name</label>
			<input type = "text" oninvalid = "alert('You must fill out the form!');" name = "first_name" id = "fname" placeholder = "Enter first name">
			<label for = "last_name">Last Name</label>
			<input type = "text" oninvalid = "alert('You must fill out the form!');" name = "last_name" id = "lname" placeholder = "Enter last name">
			<label for = "email">Email</label>
			<input type = "email" oninvalid = "alert('You must fill out the form!');" name = "email" id = "e-mail" placeholder = "Enter your email"><br/>
			<label for = "username">Username:</label>
			<input type = "text" oninvalid = "alert('You must fill out the form!');" name = "username" id = "username" placeholder = "Enter username">
			<label for = "password">Password:</label>
			<input type = "password" oninvalid = "alert('You must fill out the form!');" name = "password" id = "password" placeholder = "Enter password">
			<label for = "password_check">Password:</label>
			<input type = "password" oninvalid = "alert('You must fill out the form!');" name = "password_check" id = "pass_check" placeholder = "Enter password again">
			<a href="{% url 'home:index' %}"><button type = "submit" class = "btn btn-primary" id = "btnsubmit">Submit</button></a>
		</form>
    </div>

	</div>
	</div>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/styleregister.css' %}">
	
{% endblock %}