activity/urls.py
from django.urls import path
from . import views

app_name = "activity"

urlpatterns = [
    path('activity/', views.activity, name='activity'),
    path('result/',views.result, name = 'result'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.blog, name='blog'),
    path('id1/',views.article1, name='article1'),
    path('id2/',views.article2, name='article2'),
    path('id3/',views.article3, name='article3'),
    path('response/',views.commentReturn, name="return_comment"),
    
] 

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
    # dilanjutkan ...
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [

    path('', views.index, name='index'),
    path('signin/', views.signin_page, name='signin_page'),
    path('login_func/', views.login_func, name='login_func'),
    path('login_success/', views.login_success, name='login_success'),
    path('logout_success/', views.logout_success, name='logout_success'),
    # dilanjutkan ...
]

testimoni/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'testimoni'

urlpatterns = [
    path('', views.index, name='index'),
    #path('add_testi/', views.add_testi, name="add_testi")
    path('testjson_testi/', views.json_testi, name="json_testi")
    # dilanjutkan ...
]

tk2/urls.py
from django.contrib import admin
from django.urls import path, include
#from register.forms import RegisterForm
#from register.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('testi/', include('testimoni.urls')),
    path('',include('activity.urls')),
    path('register/',include('register.urls')),
    path('blog/',include('blog.urls')),
    #path('register/formregister', index, {'form_class': RegisterForm}),
]

testimoni/models.py
from django.db import models
from django.db import models
from django.utils import timezone
from datetime import datetime, date
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

class Testimoni(models.Model):
    nama = models.CharField(max_length=100, default="*No Name*")
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    pesan = models.TextField()
    date = models.DateTimeField(auto_now= True, blank=True)


# Create your models here.

testimoni/forms.py
from . import models
from django import forms


class TestimoniForm(forms.Form):
    rating = forms.IntegerField(min_value=1, max_value=5,
                                widget=forms.NumberInput(attrs={'required' : 'True',
                                                                'id':'rating'}))
    pesan = forms.CharField(
            widget=forms.Textarea(attrs={'required' : 'True', 'class':'form-control',
                                         'label' : 'Your testimoni', 'id':'pesan'})
							)
    
    
    

testimoni/views.py
from django.shortcuts import render, redirect
from .models import Testimoni
from .forms import TestimoniForm
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


def index(request):
    hasil = Testimoni.objects.all()
    form = TestimoniForm()
    return render(request, 'index.html', {"form": form,"testi":hasil})

def json_testi(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = TestimoniForm(request.POST)
            if form.is_valid():
                nama = request.user.get_full_name()
                rating = request.POST['rating']
                pesan = request.POST['pesan']
                hasil = Testimoni.objects.create(nama= nama, 
                                                rating = form.data['rating'],
                                                pesan = form.data['pesan'])
                hasil.save()
                json = JsonResponse({'nama':nama, 'rating':rating,'pesan':pesan}, safe=False)
                return json
    message = 'login dulu'
    response = JsonResponse({'status':'false','message':message})
    response.status_code = 403
    return response;
            
    

# Create your views here.

testimoni/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Start Your Healthy Life Here!</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Jquery -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">


    <!-- Bootstrap core CSS -->
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity=" sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'css/styleregister.css' %}">
    <link rel="stylesheet" href="{% static 'css/blogstyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styletesti.css' %}">
    <script type = "text/javascript" src = "{% static 'js/myjs.js' %}"></script>
    

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e3f2fd">
    	<a class="navbar-brand" href="{% url 'home:index' %}"><strong>Your </br> Nourishment</strong></a>
    	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        	<span class="navbar-toggler-icon"></span>
    	</button>
    	<div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'activity:activity' %}">Activity</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'testimoni:index' %}">Testimoni</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Contact Us
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="https://www.instagram.com/hnsmchl/">Instagram</a>
                <a class="dropdown-item" href="#">Whatsapp</a>
                <a class="dropdown-item" href="#">Email</a>
              </div>
            </li>
            <li class="nav-item btn btn-primary navlogin">
              <a class="nav-link" href="{% url 'register:signin_page' %}" id = "loginya" style="color: white"><div id = "label"><b>Login</b></div></a>
            </li>
          </ul>
        </div>
      </nav>
  {% block content %}
  {% endblock %}

  {% block static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="{% static 'js/testi.js' %}"></script>
  {% endblock static %}

  </body>

</html>

testimoni/templates/index.html
{% extends "base.html" %}
{% load static %}


{% block static %}
{{ block.super }}
{% endblock static %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-7">
            <div class="jumbotron jumbotron-fluid kotaktesti">
              <div class="container">
                <h1 class="display-4">Testimoni</h1>
                <p class="lead">Here are some of testimonies from our beloved customers. </br>
                	So, what are you waiting for again? Let's use our app and <strong> get healthy together </strong> !</p>
              </div>
            </div>
        </div>
        <div class="col-5">
            <!-- <div class="gambarTesti">
                <img src="{% static 'img/apaTesti.png' %}" class="gambar" alt="Responsive image">
            </div> -->
            <div class="jumbotron jumbotron-fluid kotakfunfact">
              <div class="container">
                <h1 class="display-4" style="font-size: 2em; font-weight: bold;">Fun Fact!</h1>
                <p class="lead" style="font-size: 1em">We have reach more than hundreds people. Do you ever curious why did this websites exits? <br>
                <button id="show" type="button" class="btn btn-link" style="color: #ffab40">Check this out</button> to know more about us and the history of our websites!</p>
                <p class="lead funfactpanjang" style="font-size: 1em; display: none" > Website ini merupakan perwujudan tugas kelompok dari kelompok 3 mata kuliah <strong>Perancangan dan Pemrograman Web (PPW)</strong>. Kelompok ini berisikan Nicolas, Irham, Hans, dan Maisy. Kami berharap adanya website bukan hanya sebagai pemenuhan tugas kami, tetapi juga website ini bisa bermanfaat bagi banyak orang dikemudian hari.<br> 
                    <button id="hide" type="button" class="btn btn-link" style="color: #ffab40">Hide</button></p>

              </div>
            </div>
        </div>
    </div>
</div>




<div class="container-fluid hasiltesti">
    <div class="card mb-3 testibox" style="max-width: 18rem;">
    <div class="card-header"><strong>Nicolas Henry Wijaya</strong></div>
    <div class="card-body">
        <h5 class="card-title">5 / 5</h5>
        <p class="card-text">Aplikasi ini bagus dan sangat bermanfaat bagi saya!</p>
    </div>
    </div>
    {% for isi in testi %}

    <div class="card mb-3 testibox" style="max-width: 18rem;">
        <div class="card-header"><strong> {{isi.nama}}</strong></div>
        <div class="card-body">
            <h5 class="card-title">{{isi.rating}} / 5</h5>
            <p class="card-text">{{isi.pesan}}</p>
        </div>
    </div>

    {% endfor %}
</div>

<!-- <a class="btn btn-primary buttontesti" href="{% url 'testimoni:json_testi' %}" role="button">Add Testimoni</a> -->

<!-- <a href="#" id="contactUs">Contact Us</a>                   
<div id="dialog" title="Contact form">
  <p>appear now</p>
</div> -->
<div class="jumbotron jumbotron-fluid kotaktesti">
  <div class="container">
    <h1 class="display-4">Create Your Testimoni</h1>
    <p class="lead">What's your opinion about us? Your <strong>HONEST</strong> testimoni is really help us to be better!</p>
  </div>
</div>

<form action="{% url 'testimoni:json_testi' %}" method="POST" id="formtesti">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-primary submittesti" type="submit" value="Post Testimoni">
    <a class="btn btn-danger submittesti" href="{% url 'home:index' %}" role="button">Back</a>
</form>

<div id="dialog" title="Complains" class="complain">
  <p style=" text-align:justify !important">Do you have any complain or trouble with our application? <strong>Don't worry!</strong> We are ready 24/7 to listen to your problem! <br>
  Feel free to connect with us by our <a href="https://www.instagram.com/hnsmchl/" style="color: blue">Instagram</a></p>
</div>

{% endblock %}

testimoni/templates/testiform.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron jumbotron-fluid kotaktesti">
  <div class="container">
    <h1 class="display-4">Create Your Testimoni</h1>
    <p class="lead">What's your opinion about us? Your <strong>HONEST</strong> testimoni is really help us to be better!</p>
  </div>
</div>
<form action="{% url 'testimoni:json_testi' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-primary submittesti" type="submit" value="Post Testimoni">
    <a class="btn btn-danger submittesti" href="{% url 'testimoni:index' %}" role="button">Back</a>
</form> 
</br>
<!-- <a class="btn btn-primary buttontesti" href="{% url 'home:index' %}" role="button">Post Testimoni</a> -->


{% endblock %}